[build]
  command = "yarn build && mkdir dist && cp -R .next dist/_next && cp -R .next functions/.next && yarn install:lambda && yarn build:lambda"
  publish = "dist"
  functions = ".functions"

# [[redirects]]
#   from = "/"
#   to="/.netlify/functions/server"
#   status = 200
#   force = false

# [[redirects]]
#   from = "/:hash"
#   to="/.netlify/functions/server"
#   status = 200
#   force = false

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 301
  force = false

[[redirects]]
  from="/*"
  to="/.netlify/functions/server"
  status = 200
  force = false
