[build]
  command = "yarn build"
  publish = ".next"
  functions = "functions"

[[redirects]]
  from = "/"
  to="/.netlify/functions/server"
  status = 200

[[redirects]]
  from="/*"
  to="/.netlify/functions/server/:splat"
  status = 200
  headers = {X-From = "Netlify"}
