[build]
  command = "yarn build"
  publish = ".next"
  functions = ".next/serverless/pages"

[[redirects]]
  from = "/"
  to="/.netlify/functions/index"
  status = 200

[[redirects]]
  from="/*"
  to="/.netlify/functions/:splat"
  status = 200
  headers = {X-From = "Netlify"}
