[build]
  command = "yarn build && cp -R .next functions/.next && yarn install:lambda && yarn build:lambda"
  publish = ".next"
  functions = ".functions"

[[redirects]]
  from = "/"
  to="/.netlify/functions/server"
  status = 200
  force = false

# [[redirects]]
#   from="/*"
#   to="/.netlify/functions/server?page=:splat"
#   status = 200
#   headers = {X-From = "Netlify"}
#   force = false
