[build]
  command = "yarn build && yarn install:lambda && yarn build:lambda"
  publish = "public"
  functions = ".functions"

[[redirects]]
  from="/*"
  to="/.netlify/functions/server/:splat"
  status = 200
  headers = {X-From = "Netlify"}
