[build]
  command = "yarn build && yarn install:lambda && yarn build:lambda"
  publish = "public"
  functions = ".functions"

[[redirects]]
  from = "/"
  to="/.netlify/functions/server"
  status = 200
  force = false

[[redirects]]
  from="/*"
  to="/.netlify/functions/server?page=:splat"
  status = 200
  headers = {X-From = "Netlify"}
  force = false
